# Generated by Django 5.0.14 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
