# Generated by Django 5.0.14 on 2026-08-13 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quanly_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quanly_audit_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='quanly_audi_user_id_cfea82_idx'), models.Index(fields=['action', '-created_at'], name='quanly_audi_action_602f7a_idx')],
            },
        ),
    ]
