# Generated by Django 5.2.17 on 2026-08-09 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('inst_type', models.CharField(choices=[('SPOT', '现货'), ('SWAP', '永续合约')], max_length=8)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', '买'), ('sell', '卖')], max_length=4)),
                ('pos_side', models.CharField(choices=[('long', '多'), ('short', '空'), ('net', '净')], default='net', max_length=5)),
                ('ord_type', models.CharField(choices=[('market', '市价'), ('limit', '限价')], max_length=8)),
                ('px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('sz', models.DecimalField(decimal_places=8, max_digits=24)),
                ('td_mode', models.CharField(default='cash', max_length=10)),
                ('lever', models.IntegerField(default=1)),
                ('tp_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('sl_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('state', models.CharField(choices=[('pending', '待成交'), ('live', '挂单中'), ('filled', '已成交'), ('canceled', '已撤销')], default='pending', max_length=10)),
                ('filled_sz', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('avg_px', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('exchange_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('inst_type', models.CharField(choices=[('SPOT', '现货'), ('SWAP', '永续合约')], default='SWAP', max_length=8)),
                ('symbol', models.CharField(max_length=32)),
                ('pos_side', models.CharField(choices=[('long', '多'), ('short', '空'), ('net', '净')], default='long', max_length=5)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('avg_px', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('lever', models.IntegerField(default=1)),
                ('margin', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('sz', models.DecimalField(decimal_places=8, max_digits=24)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.order')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('ccy', models.CharField(max_length=16)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('frozen', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'env', 'ccy')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'env', 'state'], name='trading_ord_user_id_f45561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('user', 'env', 'symbol', 'pos_side')},
        ),
    ]
