# Generated by Django 5.2.17 on 2026-08-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('bill_type', models.CharField(choices=[('trade', '交易'), ('close_pnl', '平仓盈亏'), ('fee', '手续费')], max_length=12)),
                ('ccy', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('balance_after', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['user', 'env'], name='trading_bil_user_id_290b83_idx')],
            },
        ),
    ]
