# Generated by Django 5.2.17 on 2026-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='opt_type',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inst_type',
            field=models.CharField(choices=[('SPOT', '现货'), ('MARGIN', '杠杆'), ('SWAP', '永续合约'), ('FUTURES', '交割合约'), ('OPTION', '期权'), ('ETF', '杠杆ETF')], max_length=8),
        ),
        migrations.AlterField(
            model_name='position',
            name='inst_type',
            field=models.CharField(choices=[('SPOT', '现货'), ('MARGIN', '杠杆'), ('SWAP', '永续合约'), ('FUTURES', '交割合约'), ('OPTION', '期权'), ('ETF', '杠杆ETF')], default='SWAP', max_length=8),
        ),
    ]
