# Generated by Django 5.2.17 on 2026-08-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_order_expiry_order_opt_type_order_strike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liq_px',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
    ]
