# Generated by Django 5.2.17 on 2026-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_position_liq_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
