# Generated by Django 5.2.17 on 2026-08-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('flexible', '活期理财'), ('fixed', '定期理财'), ('dual', '双币理财'), ('staking', 'Staking 质押'), ('loan', '借贷')], max_length=12)),
                ('ccy', models.CharField(default='USDT', max_length=16)),
                ('apr', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('term_days', models.IntegerField(default=0)),
                ('min_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('principal', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('earnings', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financeproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('ccy', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('from_acct', models.CharField(max_length=24)),
                ('to_acct', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
