# Generated by Django 5.2.17 on 2026-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeholding',
            name='product',
        ),
        migrations.RemoveField(
            model_name='financeholding',
            name='user',
        ),
        migrations.DeleteModel(
            name='FinanceProduct',
        ),
        migrations.DeleteModel(
            name='FinanceHolding',
        ),
    ]
