# Generated by Django 5.0.14 on 2026-08-17 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_strategy', '0002_add_name_to_strategy_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('bar', models.CharField(default='1m', max_length=8)),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('params', models.JSONField(default=dict)),
                ('init_cash', models.FloatField(default=10000.0)),
                ('fee_rate', models.FloatField(default=0.001)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('metrics', models.JSONField(default=dict)),
                ('equity_curve', models.JSONField(default=list)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backtests', to='core_strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('ts', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('sz', models.FloatField()),
                ('fee', models.FloatField()),
                ('pnl', models.FloatField(default=0.0)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core_backtest.backtest')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['user', '-created_at'], name='core_backte_user_id_b9c116_idx'),
        ),
    ]
