# Generated by Django 5.2.17 on 2026-08-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='okx', max_length=16)),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('label', models.CharField(default='default', max_length=64)),
                ('api_key', models.CharField(max_length=128)),
                ('secret_enc', models.TextField()),
                ('passphrase_enc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exchange', 'env', 'label')},
            },
        ),
    ]
