# Generated by Django 5.2.17 on 2026-08-09 14:45

import apps.strategy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('language', models.CharField(default='python', max_length=16)),
                ('source', models.TextField()),
                ('kind', models.CharField(choices=[('builtin', '内置'), ('uploaded', '自定义')], default='uploaded', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', '模拟盘'), ('live', '实盘')], max_length=4)),
                ('symbol', models.CharField(default='BTC-USDT', max_length=32)),
                ('interval_sec', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', '启动中'), ('running', '运行中'), ('stopped', '已停止'), ('error', '异常')], default='pending', max_length=10)),
                ('container_id', models.CharField(blank=True, default='', max_length=80)),
                ('run_token', models.CharField(default=apps.strategy.models.gen_run_token, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.exchangecredential')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=8)),
                ('message', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='strategy.strategyrun')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
