# Generated by Django 5.2.17 on 2026-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrun',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
