# Generated by Django 5.2.17 on 2026-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategyrun_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='strategy',
            name='mode',
            field=models.CharField(choices=[('code', '代码'), ('visual', '可视化')], default='code', max_length=8),
        ),
        migrations.AddField(
            model_name='strategy',
            name='visual_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
