# Generated by Django 5.0.14 on 2026-08-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('builtin', 'Built-in'), ('uploaded', 'Uploaded')], default='builtin', max_length=16)),
                ('code_ref', models.CharField(max_length=128)),
                ('default_params', models.JSONField(default=dict)),
                ('is_builtin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', 'Simulated'), ('live', 'Live')], max_length=8)),
                ('symbol', models.CharField(max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('run_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=16)),
                ('container_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategy_runs', to='core_credentials.credential')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core_strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', 'Simulated'), ('live', 'Live')], max_length=8)),
                ('inst_type', models.CharField(default='SPOT', max_length=8)),
                ('inst_id', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('ord_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=16)),
                ('sz', models.CharField(max_length=32)),
                ('px', models.CharField(blank=True, default='', max_length=32)),
                ('td_mode', models.CharField(default='cash', max_length=16)),
                ('okx_ord_id', models.CharField(db_index=True, max_length=64)),
                ('cl_ord_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_orders', to='core_credentials.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_orders', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_orders', to='core_strategy.strategyrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('buy', 'Buy'), ('sell', 'Sell'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=8)),
                ('message', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core_strategy.strategyrun')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['user', '-created_at'], name='core_strate_user_id_66f2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['run_token_hash'], name='core_strate_run_tok_8bf9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyorder',
            index=models.Index(fields=['run', '-created_at'], name='core_strate_run_id_d11c15_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyorder',
            index=models.Index(fields=['okx_ord_id'], name='core_strate_okx_ord_a1951f_idx'),
        ),
    ]
