# Generated by Django 5.0.14 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrun',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
