# Generated by Django 5.0.14 on 2026-08-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_strategy', '0002_add_name_to_strategy_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategy',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='strategy',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='strategy',
            name='template_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16),
        ),
    ]
