# Generated by Django 5.0.14 on 2026-08-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_strategy', '0003_strategy_description_strategy_owner_strategy_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='check_report',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='strategy',
            name='check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='strategy',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='source_type',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('uploaded', 'Template'), ('code', 'User Code')], default='builtin', max_length=16),
        ),
    ]
