# Generated by Django 5.0.14 on 2026-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_strategy', '0004_strategy_check_report_strategy_check_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='rule_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='source_type',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('uploaded', 'Template'), ('code', 'User Code'), ('visual', 'Visual')], default='builtin', max_length=16),
        ),
    ]
