# Generated by Django 5.2.17 on 2026-08-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('symbol', models.CharField(default='BTC-USDT', max_length=32)),
                ('bar', models.CharField(default='1m', max_length=8)),
                ('bars', models.IntegerField(default=500)),
                ('initial_capital', models.DecimalField(decimal_places=8, default=10000, max_digits=24)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0.0005, max_digits=8)),
                ('result_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
