# Generated by Django 5.0.14 on 2026-08-14 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('sim', 'Simulated'), ('live', 'Live')], max_length=8)),
                ('inst_type', models.CharField(choices=[('SPOT', 'Spot'), ('SWAP', 'Perpetual Swap')], max_length=8)),
                ('inst_id', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('ord_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=16)),
                ('pos_side', models.CharField(blank=True, default='', max_length=8)),
                ('sz', models.CharField(max_length=32)),
                ('px', models.CharField(blank=True, default='', max_length=32)),
                ('td_mode', models.CharField(max_length=16)),
                ('reduce_only', models.BooleanField(default=False)),
                ('okx_ord_id', models.CharField(db_index=True, max_length=64)),
                ('cl_ord_id', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(default='live', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_orders', to='core_credentials.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_tradin_user_id_bfdb7a_idx'), models.Index(fields=['okx_ord_id'], name='core_tradin_okx_ord_04caba_idx')],
            },
        ),
    ]
